[package]
name = "durable7-ordered"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Neutral persistent insertion-ordered collections for Rust."

[lib]
name = "durable7_ordered"
path = "src/lib.rs"

[dependencies]
durable7-fingertree = { path = "../FingerTree" }
durable7-hamt = { path = "../Hamt" }
