<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Tools.DataStructures.Wolfram</AssemblyName>
    <RootNamespace>Tools.DataStructures.Wolfram</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tools.DataStructures.Wolfram.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tools.DataStructures.FingerTree\Tools.DataStructures.FingerTree.csproj" />
    <ProjectReference Include="..\Tools.DataStructures.Hamt\Tools.DataStructures.Hamt.csproj" />
  </ItemGroup>
</Project>
